# Generated by Django 4.2.1 on 2023-05-31 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fname',
            new_name='Fname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lname',
            new_name='Lname',
        ),
    ]
